/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.nhom5.de3.gui;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import oop.nhom5.de3.controller.CauHoi;
import oop.nhom5.de3.controller.MonHoc;

/**
 *
 * @author KING
 */
public class DanhSachChuong extends javax.swing.JFrame {
    //---Cac thuoc tinh can set o Frame SoanCauHoi   
    private javax.swing.JComboBox<String> cbChuong;
    private DefaultComboBoxModel cbChuongModel;
    //----------------------------
    private ArrayList<Integer> dsChuong;
    private ArrayList<javax.swing.JCheckBox> cbList;

    public ArrayList<Integer> getDsChuong() {
        return dsChuong;
    }   
       
    /**
     * Creates new form DanhSachChuong
     */
    public DanhSachChuong() {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
    }
    public DanhSachChuong(MonHoc monHocDangChon, CauHoi cauHoiDangChon, javax.swing.JComboBox<String> cbChuong, DefaultComboBoxModel cbChuongModel,int chucNang) {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
        
        this.cbChuong = cbChuong;
        this.cbChuongModel = cbChuongModel;

        this.dsChuong = new ArrayList();

        //---Hien thi cac CheckBox tuong ung voi so chuong cua mon hoc
        cbList = new ArrayList();
        cbList.add(jCheckBox1);
        cbList.add(jCheckBox2);
        cbList.add(jCheckBox3);
        cbList.add(jCheckBox4);
        cbList.add(jCheckBox5);
        cbList.add(jCheckBox6);
        cbList.add(jCheckBox7);
        cbList.add(jCheckBox8);
        cbList.add(jCheckBox9);
        cbList.add(jCheckBox10);
        cbList.add(jCheckBox11);
        cbList.add(jCheckBox12);
        cbList.add(jCheckBox13);
        cbList.add(jCheckBox14);
        cbList.add(jCheckBox15);
        cbList.add(jCheckBox16);
        cbList.add(jCheckBox17);
        cbList.add(jCheckBox18);
        cbList.add(jCheckBox19);
        cbList.add(jCheckBox20);
        cbList.add(jCheckBox21);
        cbList.add(jCheckBox22);
        cbList.add(jCheckBox23);
        cbList.add(jCheckBox24);

        //---Neu trc click Chinh sua thi danh dau cac chuong cua cau hoi dang chon
        if ( chucNang == 2) {
            cauHoiDangChon.getDsChuong().stream().forEach((i) -> {
                cbList.get(i - 1).setSelected(true);
            });
        }
        //---Chi setEnable cho cac chuong cua mon hoc dang chon
        int soChuong = monHocDangChon.getSoChuong();
        for (int i = 0; i < soChuong; i++) {
            cbList.get(i).setEnabled(true);
        }
        for (int i = soChuong; i < cbList.size(); i++) {
            cbList.get(i).setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        bOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chương");

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox1.setText("Chương 1");

        jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox2.setText("Chương 2");

        jCheckBox3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox3.setText("Chương 3");

        jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox4.setText("Chương 4");

        jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox5.setText("Chương 5");

        jCheckBox6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox6.setText("Chương 6");

        jCheckBox7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox7.setText("Chương 7");

        jCheckBox8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox8.setText("Chương 8");

        jCheckBox9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox9.setText("Chương 9");

        jCheckBox10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox10.setText("Chương 10");

        jCheckBox11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox11.setText("Chương 11");

        jCheckBox12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox12.setText("Chương 12");

        jCheckBox13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox13.setText("Chương 13");

        jCheckBox14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox14.setText("Chương 14");

        jCheckBox15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox15.setText("Chương 15");

        jCheckBox16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox16.setText("Chương 16");

        jCheckBox17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox17.setText("Chương 17");

        jCheckBox18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox18.setText("Chương 18");

        jCheckBox19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox19.setText("Chương 19");

        jCheckBox20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox20.setText("Chương 20");

        jCheckBox21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox21.setText("Chương 21");

        jCheckBox22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox22.setText("Chương 22");

        jCheckBox23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox23.setText("Chương 23");

        jCheckBox24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox24.setText("Chương 24");

        bOK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox16)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox19)
                            .addComponent(jCheckBox20)
                            .addComponent(jCheckBox21)
                            .addComponent(jCheckBox22)
                            .addComponent(jCheckBox23)
                            .addComponent(jCheckBox24))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox9))
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox2)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox3)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox4)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox5)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox6)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox7)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jCheckBox17)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox18)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox20)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox21)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox22)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox23)
                            .addGap(23, 23, 23)
                            .addComponent(jCheckBox24)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox10)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox11)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox12)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox13)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox14)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox15)
                        .addGap(23, 23, 23)
                        .addComponent(jCheckBox16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(bOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        //---Chuong nao duoc chon se add vao dsChuong
        for (int i = 0; i < cbList.size(); i++) {
            if (cbList.get(i).isSelected()) {
                dsChuong.add(i + 1);
            }
        }
        //---Hien thi cac chuong da chon ra ComboBox Chuong o Frame SoanCauHoi
        cbChuongModel.removeAllElements();
        for (int i=0; i < dsChuong.size(); i++) {         
            cbChuongModel.addElement("Chương " + dsChuong.get(i) );
        }
        cbChuong.setModel(cbChuongModel);
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachChuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DanhSachChuong().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    // End of variables declaration//GEN-END:variables
}
