/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.nhom5.de3.gui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import oop.nhom5.de3.controller.MonHoc;
import oop.nhom5.de3.model.IOFileBinary;

/**
 *
 * @author KING
 */
public class QuanLiMonHoc extends javax.swing.JFrame {

    private ArrayList<MonHoc> dsMonHoc;
    private MonHoc monHocDangChon;
    private final DefaultListModel listDanhSachMonHocModel;
    private boolean clickThemMonHoc;
    private boolean clickChinhSua;


    /**
     * Creates new form QuanLiMonHoc
     */
    public QuanLiMonHoc() {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);        
        listDanhSachMonHocModel = new DefaultListModel();
    }
    
    public QuanLiMonHoc(ArrayList<MonHoc> dsMonHoc) {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
        
        this.dsMonHoc = dsMonHoc;
        listDanhSachMonHocModel = new DefaultListModel();
        //---Mac dinh hien thi thong tin cua mon hoc dau tien trong danh sach
        if ( !dsMonHoc.isEmpty()) {
            initListDanhSachMonHoc();
            listDanhSachMonHoc.setSelectedIndex(0);
            monHocDangChon = this.dsMonHoc.get(0);
            tfTenMonHoc.setText(dsMonHoc.get(0).getTenMonHoc());
            tfMaHocPhan.setText(dsMonHoc.get(0).getMaHocPhan());
            spSoChuong.setValue(dsMonHoc.get(0).getSoChuong());
            taGioiThieu.setText(dsMonHoc.get(0).getGioiThieu());
        }
    }

    //Hien thi danh sach cac mon hoc da luu tren listDanhSachMonHoc
    public void initListDanhSachMonHoc() {
        dsMonHoc.stream().forEach((i) -> {
            listDanhSachMonHocModel.addElement(i.getTenMonHoc());
        });
        listDanhSachMonHoc.setModel(listDanhSachMonHocModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbThemMonHoc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTenMonHoc = new javax.swing.JTextField();
        tfMaHocPhan = new javax.swing.JTextField();
        spSoChuong = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDanhSachMonHoc = new javax.swing.JList<>();
        bLuu = new javax.swing.JButton();
        bXoa = new javax.swing.JButton();
        bOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGioiThieu = new javax.swing.JTextArea();
        lbChinhSua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí môn học");
        setLocation(new java.awt.Point(700, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách môn học");

        lbThemMonHoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbThemMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        lbThemMonHoc.setText("Thêm ");
        lbThemMonHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbThemMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemMonHocMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tên môn học :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Mã học phần :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Số chương :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Giới thiệu :");

        tfTenMonHoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfMaHocPhan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        spSoChuong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        listDanhSachMonHoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        listDanhSachMonHoc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDanhSachMonHocValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDanhSachMonHoc);

        bLuu.setBackground(new java.awt.Color(0, 0, 255));
        bLuu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bLuu.setForeground(new java.awt.Color(255, 255, 255));
        bLuu.setText("Lưu");
        bLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLuuActionPerformed(evt);
            }
        });

        bXoa.setBackground(new java.awt.Color(255, 0, 0));
        bXoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bXoa.setForeground(new java.awt.Color(255, 255, 255));
        bXoa.setText("Xóa môn học");
        bXoa.setActionCommand("Xóa");
        bXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXoaActionPerformed(evt);
            }
        });

        bOK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        taGioiThieu.setColumns(20);
        taGioiThieu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        taGioiThieu.setLineWrap(true);
        taGioiThieu.setRows(5);
        taGioiThieu.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taGioiThieu);

        lbChinhSua.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbChinhSua.setForeground(new java.awt.Color(0, 0, 255));
        lbChinhSua.setText("Chỉnh sửa");
        lbChinhSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbChinhSuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbThemMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(lbChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bLuu)
                                        .addGap(53, 53, 53)
                                        .addComponent(bXoa))
                                    .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfMaHocPhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(tfTenMonHoc, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbChinhSua))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLuu)
                    .addComponent(bXoa))
                .addGap(44, 44, 44)
                .addComponent(bOK)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbThemMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemMonHocMouseClicked
        // Khi click vao reset cac phan nhap vao
        clickThemMonHoc = true;
        clickChinhSua = false;
        //Mo khoa cac phan nhap du lieu
        tfTenMonHoc.setEditable(true);
        tfMaHocPhan.setEditable(true);
        spSoChuong.setEnabled(true);
        taGioiThieu.setEditable(true);
        tfTenMonHoc.setText("");
        tfMaHocPhan.setText("");
        spSoChuong.setValue(1);
        taGioiThieu.setText("");
        monHocDangChon = null;
    }//GEN-LAST:event_lbThemMonHocMouseClicked
    //Ghi dsMonHoc ra file
    private void writeDsMonHoc(){
        IOFileBinary.writeFile(dsMonHoc, "data/DanhSachMonHoc.dat");
    }
    private void bLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLuuActionPerformed
        //Neu click Chinh Sua thi luu lai thong tin chinh sua cua mon hoc dang chon va thay doi ten mon hoc do tren listDanhSachMonHoc
        if (clickChinhSua) {
            if (((int) spSoChuong.getValue()) <= 0) {
                JOptionPane.showMessageDialog(null, "Môn học phải có số chương ít nhất là 1. Chỉnh sửa không thành công !");
                return;
            }
            int index = listDanhSachMonHocModel.indexOf(monHocDangChon.getTenMonHoc());
            monHocDangChon.setTenMonHoc(tfTenMonHoc.getText());
            monHocDangChon.setMaHocPhan(tfMaHocPhan.getText());
            monHocDangChon.setSoChuong((int) spSoChuong.getValue());
            monHocDangChon.setGioiThieu(taGioiThieu.getText());
            //---Ghi danh sach mon hoc ra file
            this.writeDsMonHoc();
            listDanhSachMonHocModel.remove(index);
            listDanhSachMonHocModel.add(index, monHocDangChon.getTenMonHoc());
            listDanhSachMonHoc.setModel(listDanhSachMonHocModel);
            monHocDangChon = null;
            clickChinhSua = false;
            JOptionPane.showMessageDialog(null, "Chỉnh sửa thành công");
            //Khoa cac phan nhap du lieu
            tfTenMonHoc.setEditable(false);
            tfMaHocPhan.setEditable(false);
            spSoChuong.setEnabled(false);
            taGioiThieu.setEditable(false);
        } else if (clickThemMonHoc) { // Neu click vao them mon hoc thi tao ra mon hoc moi
            if (((int) spSoChuong.getValue()) <= 0) {
                JOptionPane.showMessageDialog(null, "Môn học phải có số chương ít nhất là 1. Hãy nhập lại !");
                return;
            }
            MonHoc newMonHoc = new MonHoc();
            newMonHoc.setTenMonHoc(tfTenMonHoc.getText());
            newMonHoc.setMaHocPhan(tfMaHocPhan.getText());
            newMonHoc.setSoChuong((int) spSoChuong.getValue());
            newMonHoc.setGioiThieu(taGioiThieu.getText());
            //---Them mon hoc vao dsMonHoc
            dsMonHoc.add(newMonHoc);
            //---Ghi danh sach mon hoc ra file
            this.writeDsMonHoc();
            //---Them ten mon hoc vao listDanhSachMonHoc
            listDanhSachMonHocModel.addElement(newMonHoc.getTenMonHoc());
            listDanhSachMonHoc.setModel(listDanhSachMonHocModel);
            clickThemMonHoc = false;
            JOptionPane.showMessageDialog(null, "Thêm môn học thành công");
            //Khoa cac phan nhap du lieu
            tfTenMonHoc.setEditable(false);
            tfMaHocPhan.setEditable(false);
            spSoChuong.setEnabled(false);
            taGioiThieu.setEditable(false);
        }

    }//GEN-LAST:event_bLuuActionPerformed

    private void bXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXoaActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa môn học này không?", "Hãy lựa chọn", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                for (MonHoc i : dsMonHoc) {
                    if (monHocDangChon == i) {
                        dsMonHoc.remove(i);
                        //---Xoa mon hoc tren listDanhSachMonHoc
                        listDanhSachMonHocModel.removeElement(i.getTenMonHoc());
                        listDanhSachMonHoc.setModel(listDanhSachMonHocModel);
                        try {
                            //---Xoa cac cau hoi trac nghiem va tu luan cua mon hoc nay
                            Path path = Paths.get("Tuluan" + monHocDangChon.getMaHocPhan() + ".dat");
                            Files.delete(path);
                            Path path2 = Paths.get("Tracnghiem" + monHocDangChon.getMaHocPhan() + ".dat");
                            Files.delete(path2);
                        } catch (IOException ex) {
                            System.out.println("File câu hỏi của môn học không tồn tại!");
                        }
                        tfTenMonHoc.setText("");
                        tfMaHocPhan.setText("");
                        spSoChuong.setValue(1);
                        taGioiThieu.setText("");
                        monHocDangChon = null;
                        break;
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hãy chọn môn học cần xóa");
        }
    }//GEN-LAST:event_bXoaActionPerformed

    private void listDanhSachMonHocValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDanhSachMonHocValueChanged

        // Bat su kien select, bo qua su kien deselect
        if (evt.getValueIsAdjusting()) {
            monHocDangChon = dsMonHoc.get(listDanhSachMonHoc.getSelectedIndex());
            tfTenMonHoc.setText(monHocDangChon.getTenMonHoc());
            tfMaHocPhan.setText(monHocDangChon.getMaHocPhan());
            spSoChuong.setValue(monHocDangChon.getSoChuong());
            taGioiThieu.setText(monHocDangChon.getGioiThieu());

            //Khoa cac phan nhap du lieu
            tfTenMonHoc.setEditable(false);
            tfMaHocPhan.setEditable(false);
            spSoChuong.setEnabled(false);
            taGioiThieu.setEditable(false);

            clickThemMonHoc = false;
            clickChinhSua = false;
        }
    }//GEN-LAST:event_listDanhSachMonHocValueChanged


    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bOKActionPerformed

    private void lbChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbChinhSuaMouseClicked
        if (monHocDangChon != null) {
            clickChinhSua = true;
            clickThemMonHoc = false;
            //Mo khoa cac phan nhap du lieu
            tfTenMonHoc.setEditable(true);
            tfMaHocPhan.setEditable(true);
            spSoChuong.setEnabled(true);
            taGioiThieu.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(null, "Hãy chọn môn học cần chỉnh sửa");
        }
    }//GEN-LAST:event_lbChinhSuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLiMonHoc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLuu;
    private javax.swing.JButton bOK;
    private javax.swing.JButton bXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbChinhSua;
    private javax.swing.JLabel lbThemMonHoc;
    private javax.swing.JList<String> listDanhSachMonHoc;
    private javax.swing.JSpinner spSoChuong;
    private javax.swing.JTextArea taGioiThieu;
    private javax.swing.JTextField tfMaHocPhan;
    private javax.swing.JTextField tfTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
