/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.nhom5.de3.gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import oop.nhom5.de3.controller.DeThi;
import oop.nhom5.de3.controller.MonHoc;

/**
 *
 * @author KING
 */
public class QuanLiDeThi extends javax.swing.JFrame {
    private MonHoc monHocDangChon;
    /**
     * Creates new form QuanLiDeThi
     */
    public QuanLiDeThi() {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
    }
    public QuanLiDeThi(MonHoc monHocDangChon) {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
        this.monHocDangChon = monHocDangChon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bMoDeThi = new javax.swing.JToggleButton();
        bTaoDeThi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí đề thi");

        bMoDeThi.setBackground(new java.awt.Color(51, 51, 255));
        bMoDeThi.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bMoDeThi.setForeground(new java.awt.Color(255, 255, 255));
        bMoDeThi.setText("Mở đề thi có sẵn");
        bMoDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoDeThiActionPerformed(evt);
            }
        });

        bTaoDeThi.setBackground(new java.awt.Color(51, 51, 255));
        bTaoDeThi.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bTaoDeThi.setForeground(new java.awt.Color(255, 255, 255));
        bTaoDeThi.setText("Tạo đề thi mới");
        bTaoDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTaoDeThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTaoDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMoDeThi))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bMoDeThi)
                .addGap(36, 36, 36)
                .addComponent(bTaoDeThi)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMoDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoDeThiActionPerformed
        JFileChooser fChooser = new JFileChooser();
        File dir = new File("data/dethi");
        fChooser.setCurrentDirectory(dir);
        
        FileFilter filter = new FileNameExtensionFilter("Các đề thi", "dat");
        fChooser.setFileFilter(filter);
        
        fChooser.setDialogTitle("Mở đề thi có sẵn");
        int choose = fChooser.showOpenDialog(this);
        if (choose == JFileChooser.APPROVE_OPTION) { //Danh dau ban da chap nhan OPEN/SAVE
            try {
                FileInputStream fis = new FileInputStream(fChooser.getSelectedFile());
                ObjectInputStream ois = new ObjectInputStream(fis);
                DeThi deThi = (DeThi) ois.readObject();
                ois.close();

                if ( deThi.getMonHoc().getMaHocPhan().equals(this.monHocDangChon.getMaHocPhan())) {
                    ChonCauHoi thayDoi = new ChonCauHoi(this.monHocDangChon, 1, deThi);
                    thayDoi.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Đề thi không phải của môn " + this.monHocDangChon.getTenMonHoc());
                }
            } catch (IOException | ClassNotFoundException ex) {
            }
        }
    }//GEN-LAST:event_bMoDeThiActionPerformed

    private void bTaoDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTaoDeThiActionPerformed
        TaoDeThi tdt = new TaoDeThi(this.monHocDangChon);
        tdt.setVisible(true);
    }//GEN-LAST:event_bTaoDeThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiDeThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bMoDeThi;
    private javax.swing.JToggleButton bTaoDeThi;
    // End of variables declaration//GEN-END:variables
}
