/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.nhom5.de3.gui;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import oop.nhom5.de3.controller.DapAn;

/**
 *
 * @author KING
 */
public class ThemDapAn extends javax.swing.JFrame {
    private DapAn dapAn;
    //---Thuoc tinh cua Soan cau hoi can thay doi khi them dap an
    private ArrayList<DapAn> dsDapAn;
    private DefaultListModel listDanhSachDapAnModel;
    private javax.swing.JList<String> listDanhSachDapAn;
    private DapAn dapAnDangChon;
    //---chucNang = 1 :Them dap an, = 2: Chinh sua dap an
    private int chucNang;

    
    

    /**
     * Creates new form ThemDapAn
     */
    public ThemDapAn() {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null); 
    }
    public ThemDapAn(ArrayList<DapAn> dsDapAn,DefaultListModel listDanhSachDapAnModel,javax.swing.JList<String> listDanhSachDapAn, int chucNang) {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);
        this.dsDapAn = dsDapAn;
        this.listDanhSachDapAnModel = listDanhSachDapAnModel;
        this.listDanhSachDapAn = listDanhSachDapAn;
        this.chucNang = chucNang;
    }
    public ThemDapAn(ArrayList<DapAn> dsDapAn,DefaultListModel listDanhSachDapAnModel,javax.swing.JList<String> listDanhSachDapAn, DapAn dapAnDangChon, int chucNang) {
        initComponents();
        //---Hien thi giua man hinh
        setLocationRelativeTo(null);        
        
        this.dsDapAn = dsDapAn;
        this.listDanhSachDapAnModel = listDanhSachDapAnModel;
        this.listDanhSachDapAn = listDanhSachDapAn;
        this.dapAnDangChon = dapAnDangChon;
        this.chucNang = chucNang;
        
        taNoiDung.setText(dapAnDangChon.getNoiDung());
        ckbDapAnDung.setSelected(dapAnDangChon.isDapAnDung());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNoiDung = new javax.swing.JTextArea();
        ckbDapAnDung = new javax.swing.JCheckBox();
        bOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đáp án");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Đáp án");

        taNoiDung.setColumns(20);
        taNoiDung.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        taNoiDung.setLineWrap(true);
        taNoiDung.setRows(5);
        taNoiDung.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taNoiDung);

        ckbDapAnDung.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckbDapAnDung.setText("Đáp án đúng");

        bOK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(261, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbDapAnDung)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bOK))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbDapAnDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOK)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        dapAn = new DapAn(taNoiDung.getText(), ckbDapAnDung.isSelected()); 
        if ( chucNang == 1) {
            //---Them vao dsDapAn
            dsDapAn.add(dapAn);
            //---Them vao listDanhSachDapAn
            if (dapAn.isDapAnDung()) {
                listDanhSachDapAnModel.addElement("(Đ) " + dapAn.getNoiDung());
            } else {
                listDanhSachDapAnModel.addElement(dapAn.getNoiDung());
            }
            listDanhSachDapAn.setModel(listDanhSachDapAnModel);
            listDanhSachDapAn.setSelectedIndex(listDanhSachDapAnModel.size()-1);
        } else if (chucNang ==2 ) {
            //---Chinh sua dsDapAn
            int index = dsDapAn.indexOf(dapAnDangChon);
            dsDapAn.remove(index);
            dsDapAn.add(index, dapAn);

            //---Chinh sua tren listDanhSachDapAn
            listDanhSachDapAnModel.remove(index);
            if (dapAn.isDapAnDung()) {
                listDanhSachDapAnModel.add(index, "(Đ) " + dapAn.getNoiDung());
            } else {
                listDanhSachDapAnModel.add(index, dapAn.getNoiDung());
            }
            listDanhSachDapAn.setModel(listDanhSachDapAnModel);
            listDanhSachDapAn.setSelectedIndex(index);
        }

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDapAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ThemDapAn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.JCheckBox ckbDapAnDung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taNoiDung;
    // End of variables declaration//GEN-END:variables
}
